name: Backend CD

on:
  workflow_run:
    workflows: ["Backend Docker Build"]
    types: [completed]
  workflow_dispatch:

env:
  IMAGE_REPO: algovisiondh/algovision-backend

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: SSH | Pull & Run container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euo pipefail
            IMAGE="ghcr.io/${{ env.IMAGE_REPO }}"
            SHA_TAG="sha-${{ github.sha }}"
            REMOTE_DIR="/home/ubuntu/docker/backend"
            COMPOSE_FILE="compose.yml"

            echo "${{ secrets.GHCR_READ_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin || true
            cd "$REMOTE_DIR"

            sed -i "s#ghcr.io/.*/.*:sha-.*#${IMAGE}:${SHA_TAG}#g" "$COMPOSE_FILE"
            docker compose -f "$COMPOSE_FILE" pull
            docker compose --env-file ../.env -f "$COMPOSE_FILE" up -d --wait

            curl -fsS http://localhost:8080/actuator/health > /dev/null
            docker image prune -f
