name: Deploy REST Docs to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build REST Docs
        run: ./mvnw clean test package -Dmaven.test.failure.ignore=true -Dspring.profiles.active=prod

      - name: Copy snippets into docs
        run: cp -r target/generated-snippets target/generated-docs/snippets

      - name: Upload REST Docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/generated-docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
